@VibeAPI_HostAddress = http://localhost:5153
@TodoId = 00000000-0000-0000-0000-000000000000

###
GET {{VibeAPI_HostAddress}}
Accept: application/json

###
# OpenAPI JSON (Development)
GET {{VibeAPI_HostAddress}}/openapi/v1.json
Accept: application/json

###
# Scalar UI (Development)
# Note: this endpoint serves HTML.
GET {{VibeAPI_HostAddress}}/scalar/v1

###
# List todos
GET {{VibeAPI_HostAddress}}/todos?offset=0&limit=50
Accept: application/json

###
# Get todo by id
GET {{VibeAPI_HostAddress}}/todos/{{TodoId}}
Accept: application/json

###
# Create todo
POST {{VibeAPI_HostAddress}}/todos
Content-Type: application/json
Accept: application/json

{
	"title": "Buy milk",
	"completed": false
}

###
# Update todo (full update)
PUT {{VibeAPI_HostAddress}}/todos/{{TodoId}}
Content-Type: application/json
Accept: application/json

{
	"title": "Buy oat milk",
	"completed": true
}

###
# Delete todo
DELETE {{VibeAPI_HostAddress}}/todos/{{TodoId}}
Accept: application/json

